project:
  type: website

website:
  title: "IWQT"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: call.qmd
        text: Program
      - href: index.qmd
        text: Schedule
      - href: index.qmd
        text: Posters
      - href: index.qmd
        text: Registration
      - href: index.qmd
        text: Travel/Accommodation
        

format:
  html:
    theme:
      - tux
    page-layout: article
    css: styles.css
    toc: true


